<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_SensorScaling" Id="{cc08e25f-c86e-4bb1-947f-44145df351f6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SensorScaling
VAR_INPUT
    nRawInput   : INT;
END_VAR
VAR_OUTPUT
    fOutput_V   : LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fOutput_V := INT_TO_LREAL(nRawInput) / 32767.0 * 10.0;
fOutput_V := LIMIT(0.0, fOutput_V, 10.0);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>